### ISSUE TITLE
Minimal script to reproduce graph on front page?

### ISSUE THREAD

**Issue by ghost** [locuslab/qpth#1]
Hi, thanks for releasing this useful code :+1: 

Could you please provide a minimal starter script, which can reproduce the mean run times for batch sizes 64 and 128, as shown in this graph 

https://github.com/locuslab/qpth/blob/master/images/timing.png 

from the repo's front page?

Thanks a lot.

**Comment by bamos** [comment]
Hi @AjayTalati - sorry for missing this message earlier. You can collect the data for that performance graph with the `perf` script and plot it with something like this: https://gist.github.com/bamos/8765f5ee89c3fc261122f5e9a9244da7

-Brandon.

**Comment by ghost** [comment]
Hi @bamos , 

thanks a lot :+1: , the gist script is really cool :+1: 

Kind regards,

Ajay
