### ISSUE TITLE
Test script error

### ISSUE THREAD

**Issue by ghost** [locuslab/qpth#10]
Hi Brandon @bamos,

I just tried to install and test, and got this error? Any ideas how to fix please?

(pyphi) ajay@ajay-h8-1170uk:~/PythonProjects/qpth-master$ python test.py
dp_fd:  [-0.007144  0.004729 -0.010438 -0.00625  -0.006003 -0.001188  0.003218
  0.010014 -0.001992  0.009883]
dp:  [  196.936678  -118.395094  -567.53345   -489.509252  -547.720813
   114.844011    69.658027   215.148079  1320.564678  -557.036299]
Traceback (most recent call last):
  File "test.py", line 184, in <module>
    test_dl_dp()
  File "test.py", line 109, in test_dl_dp
    npt.assert_allclose(dp_fd, dp, rtol=RTOL, atol=ATOL)
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.01
(mismatch 100.0%)
 x: array([-0.007144,  0.004729, -0.010438, -0.00625 , -0.006003, -0.001188,
        0.003218,  0.010014, -0.001992,  0.009883])
 y: array([  196.936678,  -118.395094,  -567.53345 ,  -489.509252,
        -547.720813,   114.844011,    69.658027,   215.148079,
        1320.564678,  -557.036299])

Thanks for your help,
Aj

**Comment by bamos** [comment]
Hi Aj, these are probably coming from an issue in `btrisolve`. Make sure you're using the latest version of PyTorch master with this PR: https://github.com/pytorch/pytorch/pull/1195

-Brandon.
