### ISSUE TITLE
batch qp solve with equality constraints.

### ISSUE THREAD

**Issue by jdily** [locuslab/qpth#11]
Hi, I am recently want to try to use qpth to solve some of my own problems (and combine it into optNet later).
So my qp problem include only equality constraints, no inequality constraints, and I have encounter some problems and have some questions want to ask:

1. 

Does it necessary to have ineq? Originally I tried to give a 

`e = Variable(torch.Tensor())`
as shown in the denoising example, but it raise some errros.
I found that in the code, there is 
```
_, nineq, nz = G.size()
neq = A.size(1) if A.ndimension() > 0 else 0
assert(neq > 0 or nineq > 0)
```
which suggest so.
Is it because in the ref paper (Mattingley & Boyd, 2012), it introduce a slack variable on ineq?

2. 

I am a bit confuse on how to transform my qp problem into batch form.
For example there are 1000 unknown variables to solve, among them, I have equality constraints on 100 of them (which suggest only 900 variables needed to be solve).
If I divide them into batches, e.g. batchSize = 100..
How do I set up those eq constraints (because them seems global to the problem)..

thx a lot~

**Comment by bamos** [comment]
Hi, at some point, I had a version that didn't require inequalities, but now I've assumed in some places that there are always inequality constraints. I'll merge in a PR adding some conditionals to support no inequalities. You might also be able to set an inequality constraint that's always satisfied like x_0 <= 1e8, but I'm not sure if this will hurt stability.

Batch form is for solving multiple problems at the same time, not splitting up a problem.

I'll keep this issue open until we've added support back for no inequality constraints.

**Comment by jdily** [comment]
thx for the quick reply. 
I'll first try to add a dummy ineq constraints that you described!

**Comment by jdily** [comment]
In terms of batch form, I am still a bit not sure how to do it.
In the original form, if I have a problem with around 3k variables, and I put that qp problem with eq constaints in cvxpy, and it is solved w/o problems.
My original first goal of using qpth and want to try if I can solve this problem w/o learning.
(and I will replace some part of the qp as unknown, and trying to learn them).
After my first try (sort of directly translate the thing I used in cvxpy set up to the qpth torch variables)
But it said it requires a huge chunk of memories.... so I think I must use it in the batch mode.
As the result, I am a bit confuse if it's solving multiple problems or splitting up my original problem??

thx

**Comment by bamos** [comment]
The batch mode is to take advantage of parallel batch operations when training on many examples at once. It's not for splitting up a problem and making it easier to solve as you're asking. You can see some more concrete examples in the optnet repo - https://github.com/locuslab/optnet

For that many variables, you can try using our sparse solver (though as a warning, it's still under development and you may have issues that we can work through)
