### ISSUE TITLE
mismatch between shapes of tensors in qpth/solvers/pdipm/batch.py

### ISSUE THREAD

**Issue by Altriaex** [locuslab/qpth#14]
I am using pytorch 0.4 from pytorch.org
the shape of M computed in line 83 doesn't match the shape of s. same story for M in line 88.

in specific, let m = torch.min(s, 1)[0].size()[0]. i.e. the shape of M before repeat(1,nineq).

computing M using line 83 gives a tensor of shape (1,m*nineq), which does not match the shape of s or z.

my fix:

M = torch.min(s, 1)[0]
msize = M.size()[0]
M = M.view(msize,1).repeat(1,nineq)
I = M < 0
s[I] -= M[I] - 1

I just want to know if such fix is correct.

**Comment by bamos** [comment]
Thanks! Great fix. I've just pushed it to the repo and have updated the pypi package with this change as well.

-Brandon.

**Comment by oibook13** [comment]
@bamos I think you need to tweak the code more a little bit
From
`M = M.view(M.size(0)).repeat(1, nineq)`
to (Altriaex's version)
`M = M.view(M.size(0),1).repeat(1, nineq)`
Otherwise it will run into the same error "xx doesn't match the shape of xx "

I tested it on 0.4.1 pytorch + 0.0.11 qpth.

**Comment by bamos** [comment]
Thanks @oibook13 - updated!
