### ISSUE TITLE
btrf / btrs -> btrifact / btrisolve

### ISSUE THREAD

**Issue by bobbens** [locuslab/qpth#2]
It looks like in pytorch master there is btrifact as a drop-in replacement for btrf, although btrisolve has a different API from btrs. For ease of usage it would be nice to use the mainline pytorch API instead of the forked pytorch.

**Comment by bamos** [comment]
Thanks, I'm surprised you noticed so quickly that our PR was merged into PyTorch! `qpth` is now compatible with the latest PyTorch master and uses the pivoted batch LU factorizations and solves (`btrifact/solve`) there.
