### ISSUE TITLE
True sudoku solution?

### ISSUE THREAD

**Issue by ClementPinard** [locuslab/qpth#20]
Hi thanks for this project!
I was looking into the sudoku example, which I really like because I didn't know about the LPI method for solving it in the first place.

So I looked upon some blogposts about this technique, and found [this one](https://towardsdatascience.com/using-integer-linear-programming-to-solve-sudoku-puzzles-15e9d2a70baa). Now I think I understand how we can convert constraints (all the sums that must add up to 1) to a matrix equality.

Now I'm trying to figure out the true solution to the simplified sudoku example, to remove the magical part of A and b construction :smile: 

I guess we dumped the block constraint, so that makes three sets of equality, applied to 4*4 possible indices (only one number per case, only one of each possible number per column, and only one of each possible number per row). Is it fair that it would make 48 equalities ? Shouldn't A be then of size (48,64) instead of (40,64) ?

Maybe the 48 equalities are not all independant ?

Btw, I think the markdown is a bit wrong between cell 5 and 6, I think it should be
```
y* = argmin_y 0.5 eps y^T y - p^T y
         s.t. Ay  = b
               y >= 0
```

(note the z replaced by y)

**Comment by bamos** [comment]
Yes, that's right. All 48 equalities are not all independent. Also what markdown cell are you referring to?

**Comment by bamos** [comment]
Ah, nevermind, I found and fixed that markdown cell. Thanks!

**Comment by ClementPinard** [comment]
I guess you could also change this one : https://github.com/locuslab/qpth/blob/master/example-sudoku.ipynb?short_path=1e568a8#L279

Anyway thanks for your quick answer !

**Comment by bamos** [comment]
Ah thanks! I fixed that one too. We need automated type- and syntax-checking for math. :)

Let me know if there's anything else!
