### ISSUE TITLE
Not running. btrisolve() issue

### ISSUE THREAD

**Issue by brunocuevas** [locuslab/qpth#23]
Hi

I wanted to use your QP solver because it seems the perfect solution to a problem I was facing. I need to obtain solutions of a neural network that meet some equalitiy conditions. Therefore, I considered a least-squares problem in the qp format.

![imagen](https://user-images.githubusercontent.com/15262930/61726614-32b35000-ad72-11e9-9b29-7011da80279a.png)

constrained to Qx = q. 
u is the output of my network.

I was trying to run this in the net, but I've foun the following error message

```
~\Anaconda3\lib\site-packages\qpth\solvers\pdipm\batch.py in pre_factor_kkt(Q, G, A)
    399     # for more details.
    400 
--> 401     G_invQ_GT = torch.bmm(G, G.transpose(1, 2).btrisolve(*Q_LU))
    402     R = G_invQ_GT.clone()
    403     S_LU_pivots = torch.IntTensor(range(1, 1 + neq + nineq)).unsqueeze(0) \

TypeError: btrisolve() takes 3 positional arguments but 4 were given


```

My test code (avoiding the constraints and using a dummy inequality) was:

```
u = torch.autograd.Variable(x_iso[:, :4, :].flatten().reshape(-1, 1))
I = torch.autograd.Variable(torch.eye(x.size()[0]))
G = torch.autograd.Variable(torch.eye(x.size()[0]))
h = torch.autograd.Variable(x + torch.rand(x.size()))
e = torch.autograd.Variable(torch.Tensor())
QPFunction()(I, u, G, h, e, e)

```

I've also tried to run the example at the [repo](https://github.com/locuslab/qpth/blob/master/example-cls-layer.ipynb) and I got the same error message. Also changed the solver, but the result is also an error message. I'm using python3.6 in Win10. I had disabled the cuda() options.

Thx

**Comment by bamos** [comment]
Hi -- sorry, PyTorch made some breaking changes to the batched LU factorizations/solves that I think I've fixed in master but not in the pip version of qpth. Can you try installing from master and try again, and also try updating to the latest PyTorch version if that doesn't work?

**Comment by brunocuevas** [comment]
Hi

Following the example at your [repo](https://github.com/locuslab/qpth/blob/master/example-cls-layer.ipynb), it works.

The example of OptNet on the project webpage has a tiny mistake


```
        L = self.M*self.L
        Q = L.mm(L.t()) + self.eps*Variable(torch.eye(self.nCls)).cuda()
        h = self.G.mv(self.z0)+self.s0
        e = Variable(torch.Tensor())
        x = QPFunction(verbose=False)(Q, x, G, h, e, e)

```
and in your notebook is
```
        L = self.M*self.L
        Q = L.mm(L.t()) + self.eps*Variable(torch.eye(self.nCls))
        h = self.G.mv(self.z0)+self.s0
        e = Variable(torch.Tensor())
        x = QPFunction(verbose=-1)(Q, x, self.G, h, e, e)
```

Thanks!

**Comment by bamos** [comment]
Closing this for now but let me know if there's anything else!
