### ISSUE TITLE
Non convex task solver

### ISSUE THREAD

**Issue by wimwimyam** [locuslab/qpth#26]
Hi, the idea of Optnet seems to be a perfect solution to my problem. My task is non convex, but it is proved that every local optimum is global optimum. How can I apply this package on my problem? I tried to use sequential quadratic programming but it was very slow. Is there any fast way to solve my problem? Thanks!

**Comment by wimwimyam** [comment]
I can solve the task quickly by using gradient descent, can I get the gradient information through QPFunction without solving the task? Given that I have the optimal solution, first and second derivatives at optimal point.

**Comment by bamos** [comment]
Hmm, it's probably best to implicitly differentiate the kkt conditions at one of the optimum, you may find the kkt solver in here useful
