### ISSUE TITLE
can I use this to solve LP problem?

### ISSUE THREAD

**Issue by icoz69** [locuslab/qpth#27]
Hello
can I easily modify the code to work on Linear Program prblem?

**Comment by bamos** [comment]
Yes, you can add a small ridge penalty like in the sudoku example

**Comment by icoz69** [comment]
Hi
I try to use your code to slove a LP problem with two ways.
Given a linear program with the following form
minimize FX
subject to : AX=B X>0
 
1.my first way is to set the Q to a diagonal matrix with all ones, and multiply the Q with a small value , e.g. 0.00001.  In this case, I did find the slover is optimizing, but the final result is not ideal. 

2.my second way is to transform the object function to QP form: (X^T)(F^T)(F)(X). and set the q to zeros. The optimal X should be the same. However, the result is far from the correct one. The objective function reaches zero but  it totally ignores the constrains

Can I some advice about how to correctly use it solve the LP problem?

@bamos

**Comment by bamos** [comment]
If you're using floats instead of doubles can you try using doubles and see if that helps with stability?

**Comment by icoz69** [comment]
Hi, i tried double dtype, and it does not help much.  it seems constrains are not very strong
