### ISSUE TITLE
Cannot perform LU factorization on Q

### ISSUE THREAD

**Issue by noUmbrella** [locuslab/qpth#28]
Hi, I want to solve 2-classes SVM in Euclidean space using your qpth. Here is my test code.

batch_size = 2
sample_num = 3
sample_dim = 4

X = torch.rand(batch_size, sample_num, sample_dim).cuda(3)
Y = torch.rand(batch_size, sample_num).cuda(3)
Y[Y>0.8], Y[Y<=0.8] = 1, -1

DY = torch.zeros(batch_size, sample_num, sample_num).cuda(3)
DY.as_strided(Y.size(), [DY.stride(0), DY.size(2) + 1]).copy_(Y)

Q = torch.eye(sample_dim).repeat(batch_size, 1, 1).cuda(3)
p = torch.Tensor().cuda()
A = torch.Tensor().cuda()
b = torch.Tensor().cuda()
G = -torch.matmul(DY, X)
h = -torch.ones(batch_size, sample_num)
w = QPFunction(verbose=False)(Q, p, G, h, A, b)

I set Q as an eye matrix, but it reports error as 'qpth Error: Cannot perform LU factorization on Q. Please make sure that your Q matrix is PSD and has a non-zero diagonal.' Why? What should I do? Thanks for your attention.

**Comment by noUmbrella** [comment]
My pytorch version is 0.4.1

**Comment by bamos** [comment]
Can you try updating to the latest pytorch version? qpth doesn't support older versions

**Comment by noUmbrella** [comment]
Hi, I think pytorch0.4.1 is relatively new, and I have seen some work citing qpth run with pytorch0.4.1. Would you like to run my code on your machine and software. Thanks!@bamos

**Comment by kjunelee** [comment]
Adding small constant times identity matrix to the kernel matrix 
as in
https://github.com/kjunelee/MetaOptNet/blob/master/models/classification_heads.py#L363
can help mitigate such issues.

**Comment by noUmbrella** [comment]
Thanks for your reply! For test, I set Q as an identity matrix rather than kernel matrix. It satisfies all the properties of kernel matrix. But qpth does not work.
@kjunelee

**Comment by noUmbrella** [comment]
Besides, I do not want to solve SVM in dual space, but in Euclidean space.
@kjunelee

**Comment by noUmbrella** [comment]
I have solved this problem after using pytorch1.0, thanks
@bamos

**Comment by bamos** [comment]
Great!
