### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by noUmbrella** [locuslab/qpth#29]
When I run qpth in pytorch1.1, it shows that the 'factor_kkt_eye = torch.eye(nineq).repeat(nBatch, 1, 1).type_as(R).bool()' in 'qpth/solvers/pdipm/batch.py' is error because tensor hass no attribute bool.

**Comment by bamos** [comment]
Can you try with pytorch 1.3? This should still work

```python
>>> import torch
torc>>> torch.__version__
'1.3.0.dev20190907'
>>> torch.randn(4).bool()
tensor([True, True, True, True])
```
