### ISSUE TITLE
Query for Equation (7) and (8) in main paper

### ISSUE THREAD

**Issue by vanoracai** [locuslab/qpth#30]
Hello,
I'm reading this paper recently while get some problems in understanding the equations in your main paper. 

May I ask how can I get  Equation (7) to (6) and how to get Equation(8)? I can only understand the inverse multiplication of the left-hand-side matrix while confused about the right part of [(al/az*)^T,0,0]^T . Could you pls explain more on the derivation?

Thank you！

**Comment by bamos** [comment]
Sorry, the derivation is somewhat messy there with the matrix differentials. Shane Barratt (@sbarratt) has a nice writeup of a similar derivation here: https://arxiv.org/abs/1804.05098
