### ISSUE TITLE
Infeasibility

### ISSUE THREAD

**Issue by sjcszw** [locuslab/qpth#31]
Hello,

When we use cvx as solver, the problem may become infeasible. How can we deal with this problem? Actually, we noticed that the qpth never throw infeasible error, in this case, what does the gradient mean? Because the gradient is derived from KKT system, if the original problem is infeasible, there is no solution to the KKT system. Therefore the gradient doesn't seem to have any rigorous math meaning.

Many thanks
Jicheng

**Comment by bamos** [comment]
It's hard to differentiate through an infeasible problem and I'm not sure the best of handling this case. In the settings I've considered, I usually formulate it so that the parameterization provably results in a feasible problem
