### ISSUE TITLE
Solving with floats sometimes gives bad solutions

### ISSUE THREAD

**Issue by bamos** [locuslab/qpth#4]
+ Sometimes solving a problem with floats gives a really bad solution. The current workaround is to convert everything to doubles.
+ @riceric22 mentioned that on the CPU, using doubles doesn't fix the bad solution problem when it does fix it with CUDA.

**Comment by bamos** [comment]
Hi @lakehanne - you mentioned earlier that you're using the CPU version. I just tried solving some easy problems on the CPU and it has some extremely bad accuracy issues even with doubles (that aren't present with doubles on the GPU) and I'm not sure what's causing them. You should check the solutions our function returns with something like this:

```
import qpth.solvers.cvxpy as qpcp
# For a single example
[Q, p, G, h, A, b] = [x.data.cpu().numpy() for x in [Q, p, G, h, A, b]]
zhats, _, _ = qpcp.forward_single_np(p, Q, G, h, A, b)
```

Let me know if you see something simple that's causing these issues. I'll try to look into this sometime soon over the next few weeks. If you need this improved quickly, you can try adding iterative refinement (#6).

-Brandon.

**Comment by bamos** [comment]
Actually, I wonder if something in the CPU versions I wrote of `btrifact` and `btrisolve` is causing this. I did add in tests to PyTorch master that pass, but maybe our usage in `qpth` hits some bad edge case. These are probably better to look into first before adding iterative refinement.

Here's a quick example:

## Code

<details>

```python
#!/usr/bin/env python3

import torch
from torch.autograd import Variable

from qpth.qp import QPFunction

nx, nineq, neq = 5, 4, 3
Q = torch.eye(nx)
p = torch.zeros(nx)
G = torch.randn(nineq, nx)
h = torch.randn(nineq)
A = torch.randn(neq, nx)
b = torch.randn(neq)

[Q, p, G, h, A, b] = [Variable(x) for x in [Q, p, G, h, A, b]]
xhat = QPFunction()(Q, p, G, h, A, b)
print('CPU float', xhat)

[Q, p, G, h, A, b] = [Variable(x.data.double()) for x in [Q, p, G, h, A, b]]
xhat = QPFunction()(Q, p, G, h, A, b)
print('CPU double', xhat)

[Q, p, G, h, A, b] = [Variable(x.data.float().cuda()) for x in [Q, p, G, h, A, b]]
xhat = QPFunction()(Q, p, G, h, A, b)
print('GPU float', xhat)

[Q, p, G, h, A, b] = [Variable(x.data.double()) for x in [Q, p, G, h, A, b]]
xhat = QPFunction()(Q, p, G, h, A, b)
print('GPU double', xhat)
```

</details>

## Output
<details>

```
empc(master*)$ ./t.py
CPU float Variable containing:
-0.2628 -0.6837 -0.5436 -0.6122 -0.3487
[torch.FloatTensor of size 1x5]

CPU double Variable containing:
-0.2628 -0.6837 -0.5436 -0.6122 -0.3487
[torch.DoubleTensor of size 1x5]

GPU float Variable containing:
 1.1078  0.4778  0.0483  0.1064 -0.3161
[torch.cuda.FloatTensor of size 1x5 (GPU 0)]

GPU double Variable containing:
 1.1078  0.4778  0.0483  0.1064 -0.3161
[torch.cuda.DoubleTensor of size 1x5 (GPU 0)]
```

</details>

**Comment by bamos** [comment]
Actually, I'm worried this will cause bad silent errors. I just added a `RuntimeError` to the `forward` call when the CPU is being used that links here and pushed this to pypi as `qpth v0.0.4`.

**Comment by bamos** [comment]
Great news! I figured out what was causing this and have fixed the issue. The problem was that `qpth` makes a tensor non-contiguous by transposing it and my `btrisolve` function assumed that the tensor was contiguous. I just fixed this in PyTorch and sent in [this PR](https://github.com/pytorch/pytorch/pull/1195), which should be merged shortly. **Please make sure you have a version of PyTorch that contains this PR if you are using qpth in CPU mode!**

-Brandon.

**Comment by bamos** [comment]
Removed `RuntimeError` and bumped version to `v0.0.5`.

**Comment by robotsorcerer** [comment]
Awesome. Thanks for the update!

Sincerely,
Lekan

**Comment by robotsorcerer** [comment]
I wanted to check if you removed the breaking portion of the code when using CPU in your PR. I just tested  the CPU code now and it says:

```bash
RuntimeError: 
Error: Not using CUDA.
qpth currently silently fails on the CPU and returns bad solutions.
We are tracking progress on this issue at:
https://github.com/locuslab/qpth/issues/4
> /home/robotec/anaconda2/envs/py36/lib/python3.6/site-packages/qpth/qp.py(82)forward()

     80 qpth currently silently fails on the CPU and returns bad solutions.
     81 We are tracking progress on this issue at:
---> 82 https://github.com/locuslab/qpth/issues/4""")
        global https = undefined
        global github.com = undefined
        global locuslab = undefined
        global qpth = undefined
        global issues = undefined

RuntimeError: 
Error: Not using CUDA.
qpth currently silently fails on the CPU and returns bad solutions.
We are tracking progress on this issue at:
https://github.com/locuslab/qpth/issues/4
> /home/robotec/anaconda2/envs/py36/lib/python3.6/site-packages/qpth/qp.py(82)forward()
     80 qpth currently silently fails on the CPU and returns bad solutions.
     81 We are tracking progress on this issue at:
---> 82 https://github.com/locuslab/qpth/issues/4""")
```

I'm on qpth-0.0.4 and Pytorch commit [e7f522](https://github.com/pytorch/pytorch/commit/e7f5220dfa2eafcf7a17c9e332caf9053d7dd21b)

**Comment by bamos** [comment]
Oops, I forgot to push qpth-0.0.5 to pip after creating it yesterday, which has this removed. I just pushed it, can you update your qpth version? Also does anybody know if there's an easier, more automatic way to deploy to pip? (like if the version in setup.py changes)

s/pip/pypi
