### ISSUE TITLE
Missing comma in setup.py file uploaded to pipy. 

### ISSUE THREAD

**Issue by ascientist** [locuslab/qpth#52]
While installing qpth using` pip install qpth` I encountered this bug. Seems to be ok on the github repo but the downloaded archive from pipy confirmed the missing comma. 

```
Collecting qpth
  Downloading qpth-0.0.15.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in qpth setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          **numpy>=1<2**
               ~~~^
      [end of output]
```

**Comment by Ingvar-Y** [comment]
@bamos could you make a new release on PyPI with latest February fixes, please? It will fix this issue.
Could you also release it on conda-forge? I can assist with it if necessary.

**Comment by bamos** [comment]
> @bamos could you make a new release on PyPI with latest February fixes, please?

Yeah, I just bumped the version and pushed the latest to PyPi

>  It will fix this issue. Could you also release it on conda-forge? I can assist with it if necessary.

Can you make the the pypi version or a local copy work for you? I'd prefer not to put on conda-forge as it's a relatively small project that I'm mostly not maintaining anymore

**Comment by Ingvar-Y** [comment]
@bamos I can do with PyPI version but having everything on conda-forge is just more convenient. I can maintain the conda-forge feedstock by myself without you, it is actually pretty easy after initial setting up, I just need your consent for that.
