### ISSUE TITLE
Appears there is an unnecessary loop in check_Q_spd

### ISSUE THREAD

**Issue by trentonbrochill** [locuslab/qpth#55]
https://github.com/locuslab/qpth/blob/0ccf2d73a299eda00f597406e2dd00bf97ba728a/qpth/qp.py#L82

>            if check_Q_spd:
>                for i in range(nBatch):
>                    try:
>                        torch.linalg.cholesky(Q)
>                    except:
>                        raise RuntimeError('Q is not SPD.')`

The Q variable is not updated in the loop, so loop over nBatch will produce same result every time

**Comment by bamos** [comment]
Thanks, good spot. I just pushed in a fix to this
