### ISSUE TITLE
Support non-default GPUs

### ISSUE THREAD

**Issue by xuwkk** [locuslab/qpth#56]
https://github.com/locuslab/qpth/blob/ead299eb363b552de6626da470a688d16d27f661/qpth/solvers/pdipm/batch.py#L11-L17

Not a big issue. See above lines. Simply change the `.cuda()` to `.to(x.device)` will allow the the non-default gpu.

Many thanks.

**Comment by bamos** [comment]
Thanks! I just fixed this and pushed a new version to pypi
