### ISSUE TITLE
Is the Sinkhorn Knopp algorithm possible?

### ISSUE THREAD

**Issue by ghost** [locuslab/qpth#9]
Hi @bamos,

I'm just getting started with `qpth` and am just a beginner with mathematical optimisation. To be honest I'm not so sure I know what I'm doing? 

Can I ask you advice please? Is it possible to implement the simple `1D` Sinkhorn Knopp algorithm, (to approximate the earth movers distance), using `qpth`? It's not a complicated quadratic program, and doesn't have to be efficient, just understandable :+1: 

The algorithms implemented in numpy here, (right at the top)

https://github.com/rflamary/POT/blob/master/ot/bregman.py

and it's also been implemented as a loss layer in `mocha.jl`, here

https://github.com/pluskid/Mocha.jl/blob/master/src/layers/wasserstein-loss.jl#L70

so I guess it should be possible? I just don't know how to do it with `qpth`, in `pytorch`? 

It definitely doe'st need any thing complicated as it can be done in about 10 lines in MATLAB,

https://uk.mathworks.com/matlabcentral/fileexchange/52930-sinkhorn-knopp-algorithm-for-matrix-normalisation?focused=5332757&tab=function

Thank you very much for your help :+1:

**Comment by bamos** [comment]
Hi @AjayTalati - I'm not familiar with the SK algorithm but you should be able to solve it with `qpth` if it's a QP.

-Brandon.

**Comment by ghost** [comment]
Hi Brandon @bamos, thanks a lot for taking the time to reply :+1: 

The SK algorithms not really even a `LP`, let alone a `QP`, it just basically iterate's row and column normalisation. It's used to approximate the earth movers distance, which is usually solved using a `LP`, but that's really slow? 

Here's a short description, 

> The Sinkhorn-Knopp algorithm takes a matrix A and finds diagonal matrices D and E such that if M = DAE the sum of each column and each row of M is unity. The method is, in effect, to alternately normalise the rows and the columns of the matrix. This function is an efficient implementation which does not actually carry out normalisation until the iteration is complete and which does not use the transpose of A. A matrix whose rows and columns all sum to unity is termed "doubly stochastic". 

Thanks once again,

Best, Ajay
